---
# tasks file for common

  - name: Set timezone Samara.
    timezone:
      name: Europe/Samara

  - name: Import EPEL GPG key.
    rpm_key:
      key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"      
      state: present

  - name: Install EPEL repo.
    dnf:
      name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
      state: present

  - name: Install packages
    dnf:
      name:
      - openssl-devel
      - libffi-devel
      - git
      - bash-completion
      - lsscsi
      - mtr
      - nfs-utils
      - parted
      - pciutils
      - policycoreutils-python-utils
      - rsync
      - net-tools
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - lsof
      - gcc
      state: present
     
  - name: stop selinux
    command: setenforce 0
  
  - name: disable selinux
    selinux:
      state: disabled